PROTOCOLS = {
    "3A": {"tissue": "Whole blood", "preservation": "Snap Frozen", "layer": "Clinically_accessible",
           "tissue_abv": "BLOO", "DedupKey": "D01", "color": "#FF382E"},
    "3B": {"tissue": "Buccal Swab", "preservation": "Fresh", "layer": "Clinically_accessible",
           "tissue_abv": "BUCC", "DedupKey": "D02", "color": "#75001F"},
    "3C": {"tissue": "Esophagus", "preservation": "Snap Frozen", "layer": "Endoderm",
           "tissue_abv": "ESOP", "DedupKey": "D03", "color": "#FFB161"},
    "3D": {"tissue": "Esophagus", "preservation": "Fixed", "layer": "Endoderm",
           "tissue_abv": "ESOP", "DedupKey": "D03", "color": "#FFB161"},
    "3E": {"tissue": "Colon-Ascending", "preservation": "Snap Frozen", "layer": "Endoderm",
           "tissue_abv": "COAS", "DedupKey": "D04", "color": "#C0B5E7"},
    "3F": {"tissue": "Colon-Ascending", "preservation": "Fixed", "layer": "Endoderm",
           "tissue_abv": "COAS", "DedupKey": "D04", "color": "#C0B5E7"},
    "3G": {"tissue": "Colon-Descending", "preservation": "Snap Frozen", "layer": "Endoderm",
           "tissue_abv": "COAD", "DedupKey": "D04", "color": "#9D4BBF"},
    "3H": {"tissue": "Colon-Descending", "preservation": "Fixed", "layer": "Endoderm",
           "tissue_abv": "COAD", "DedupKey": "D04", "color": "#9D4BBF"},
    "3I": {"tissue": "Liver", "preservation": "Snap Frozen", "layer": "Endoderm",
           "tissue_abv": "LIVR", "DedupKey": "D05", "color": "#FF4AA9"},
    "3J": {"tissue": "Liver", "preservation": "Fixed", "layer": "Endoderm",
           "tissue_abv": "LIVR", "DedupKey": "D05", "color": "#FF4AA9"},
    "3K": {"tissue": "Adrenal Gland, L", "preservation": "Snap Frozen", "layer": "Mesoderm",
           "tissue_abv": "ADGL", "DedupKey": "D06", "color": "#EA7A00"},
    "3L": {"tissue": "Adrenal Gland, L", "preservation": "Fixed", "layer": "Mesoderm",
           "tissue_abv": "ADGL", "DedupKey": "D06", "color": "#EA7A00"},
    "3M": {"tissue": "Adrenal Gland, R", "preservation": "Snap Frozen", "layer": "Mesoderm",
           "tissue_abv": "ADGR", "DedupKey": "D06", "color": "#EA7A00"},
    "3N": {"tissue": "Adrenal Gland, R", "preservation": "Fixed", "layer": "Mesoderm",
           "tissue_abv": "ADGR", "DedupKey": "D06", "color": "#EA7A00"},
    "3O": {"tissue": "Aorta", "preservation": "Snap Frozen", "layer": "Mesoderm",
           "tissue_abv": "AORT", "DedupKey": "D07", "color": "#F99B9B"},
    "3P": {"tissue": "Aorta", "preservation": "Fixed", "layer": "Mesoderm",
           "tissue_abv": "AORT", "DedupKey": "D07", "color": "#F99B9B"},
    "3Q": {"tissue": "Lung", "preservation": "Snap Frozen", "layer": "Endoderm",
           "tissue_abv": "LUNG", "DedupKey": "D08", "color": "#1DDD30"},
    "3R": {"tissue": "Lung", "preservation": "Fixed", "layer": "Endoderm",
           "tissue_abv": "LUNG", "DedupKey": "D08", "color": "#1DDD30"},
    "3S": {"tissue": "Heart, LV", "preservation": "Snap Frozen", "layer": "Mesoderm",
           "tissue_abv": "HART", "DedupKey": "D09", "color": "#DDD824"},
    "3T": {"tissue": "Heart, LV", "preservation": "Fixed", "layer": "Mesoderm",
           "tissue_abv": "HART", "DedupKey": "D09", "color": "#DDD824"},
    "3U": {"tissue": "Testis, L", "preservation": "Snap Frozen", "layer": "Germinal",
           "tissue_abv": "TESL", "DedupKey": "D10", "color": "#AAF8B4"},
    "3V": {"tissue": "Testis, L", "preservation": "Fixed", "layer": "Germinal",
           "tissue_abv": "TESL", "DedupKey": "D10", "color": "#AAF8B4"},
    "3W": {"tissue": "Testis, R", "preservation": "Snap Frozen", "layer": "Germinal",
           "tissue_abv": "TESR", "DedupKey": "D10", "color": "#AAF8B4"},
    "3X": {"tissue": "Testis, R", "preservation": "Fixed", "layer": "Germinal",
           "tissue_abv": "TESR", "DedupKey": "D10", "color": "#AAF8B4"},
    "3Y": {"tissue": "Ovary, L", "preservation": "Snap Frozen", "layer": "Germinal",
           "tissue_abv": "OVAL", "DedupKey": "D11", "color": "#FFAFD4"},
    "3Z": {"tissue": "Ovary, L", "preservation": "Fixed", "layer": "Germinal",
           "tissue_abv": "OVAL", "DedupKey": "D11", "color": "#FFAFD4"},
    "3AA": {"tissue": "Ovary, R", "preservation": "Snap Frozen", "layer": "Germinal",
            "tissue_abv": "OVAR", "DedupKey": "D11", "color": "#FFAFD4"},
    "3AB": {"tissue": "Ovary, R", "preservation": "Fixed", "layer": "Germinal",
            "tissue_abv": "OVAR", "DedupKey": "D11", "color": "#FFAFD4"},
    "3AC": {"tissue": "Dermal Fibroblast", "preservation": "Cultured Cells",  "layer": "Cultured_Cells",
            "tissue_abv": "FBRO", "DedupKey": "D12", "Notes": "Isolated from fresh calf skin", "color": "#FFE98D"},
    "3AD": {"tissue": "Skin-Calf", "preservation": "Snap Frozen", "layer": "Ectoderm",
            "tissue_abv": "SKSE", "DedupKey": "D13", "color": "#0EC1B8"},
    "3AE": {"tissue": "Skin-Calf", "preservation": "Fixed", "layer": "Ectoderm",
            "tissue_abv": "SKSE", "DedupKey": "D13", "color": "#0EC1B8"},
    "3AF": {"tissue": "Skin-Abdomen", "preservation": "Snap Frozen", "layer": "Ectoderm",
            "tissue_abv": "SKNE", "DedupKey": "D13", "color": "#91E5DB"},
    "3AG": {"tissue": "Skin-Abdomen", "preservation": "Fixed", "layer": "Ectoderm",
            "tissue_abv": "SKNE", "DedupKey": "D13", "color": "#91E5DB"},
    "3AH": {"tissue": "Skeletal Muscle", "preservation": "Snap Frozen", "layer": "Mesoderm",
            "tissue_abv": "MUSC", "DedupKey": "D14", "color": "#AA9A41"},
    "3AI": {"tissue": "Skeletal Muscle", "preservation": "Fixed", "layer": "Mesoderm",
            "tissue_abv": "MUSC", "DedupKey": "D14", "color": "#AA9A41"},
    "3AJ": {"tissue": "Brain", "preservation": "Fresh", "layer": "Ectoderm",
            "tissue_abv": "BRAI", "DedupKey": "D15", "color": "#BBE7FF"},
    "3AK": {"tissue": "Brain-Frontal lobe", "preservation": "Snap Frozen", "layer": "Ectoderm",
            "tissue_abv": "BRFL", "DedupKey": "D15", "color": "#BBE7FF"},
    "3AL": {"tissue": "Brain-Temporal lobe", "preservation": "Snap Frozen", "layer": "Ectoderm",
            "tissue_abv": "BRTL", "DedupKey": "D15", "color": "#76AEFF"},
    "3AM": {"tissue": "Brain-Cerebellum", "preservation": "Snap Frozen", "layer": "Ectoderm",
            "tissue_abv": "BRCE", "DedupKey": "D15", "color": "#1655C4"},
    "3AN": {"tissue": "Brain-Hippocampus, L", "preservation": "Snap Frozen", "layer": "Ectoderm",
            "tissue_abv": "BRHL", "DedupKey": "D15", "color": "#002A66"},
    "3AO": {"tissue": "Brain-Hippocampus, R", "preservation": "Snap Frozen", "layer": "Ectoderm",
            "tissue_abv": "BRHR", "DedupKey": "D15", "color": "#002A66"},
}
